import figure_1
import figure_2
import figure_3
import figure_4
import figure_5
import figure_6
import figure_7
import figure_8
import figure_9
import figure_10
import supplemental_figure_1
import supplemental_figure_2